sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: YN7U8g6V/nFUhOwa8MiE0wCpVWedbgEpEekmM3jD9NVSanNfHYL38Kk2bHPWS6TTy1zMGmqF8oOWRueE9Knv0qeHkoJRiSRs/ZblLrrFKxqKO8yuhe0XErPcHpZQThLm9kxsL/6ngIYN9LsSoyZuSvF6mFdsr5MozV4OjRmg3ywi/pvCff7gO926errDHRnsKtP/cW/3UUrmiXwOptxKF/KRHmNd/F1u6AShGKpyjhJJUT1gLIhHvwftXvqVqURjBE6QlbtP+jD5OyQHKZzI07P3mFf6YuTuK8ConV/u9VOHywvKPeWI1q8sKImfpZEzuFW1ShJReGxIYgqKklf5Ge2JmtYfrPUTmlPt/nvBPTbskC8kIJuk8TfFEJy7pFN5ZzDYyq+gxOLF/EBu1daQV1LDLCf43+8965uuG9Wj5SoM4ICREOB7T9yKJaNwchG2DixN09haaOD3PJnQuw4iiB+A637MXJsp57+NmOehDKFMRAPw7LS8vmiNMArURCX+kNiXfJezJfU3oKXafTNQBgQhCLrd257f4cgw5Hvr8Wq/vX9pTSZHRWrMxGZGo+M6V+DwMShRaGn24WvK9pqxb/BcS7xh0Oo58g//9nARcKjrquoaSyFZ53+WX1v+1r0C+uuBlQJzjpBtyFmdSWfiITRo6SRv5ZUezTxxHds8JPI=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Heart-of-the-West_1725
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy